#!/usr/bin/env bash
# Writes serenity-trader-stack/today.md with current dates + market state.
# Run this manually before each Claude Code session, or via cron @hourly.
set -e
OUT="/home/qbao775/serenity-trader-stack/today.md"
{
    echo "# Today (auto-refreshed)"
    echo ""
    echo "- UTC:  $(date -u '+%Y-%m-%d %H:%M:%S')"
    echo "- NZT:  $(TZ='Pacific/Auckland' date '+%Y-%m-%d %H:%M:%S %Z')"
    echo "- EDT:  $(TZ='America/New_York' date '+%Y-%m-%d %H:%M:%S %Z')"
    echo "- HKT:  $(TZ='Asia/Hong_Kong' date '+%Y-%m-%d %H:%M:%S %Z')"
    echo ""
    echo "## Market state (rough)"
    echo "- US RTH:  9:30-16:00 EDT (M-F)"
    echo "- HK:      9:30-12:00 + 13:00-16:00 HKT (M-F)"
    echo ""
    echo "_Regenerated by scripts/refresh-today.sh — re-read before any new thesis to anchor 'today'._"
} > "$OUT"
echo "✓ $OUT updated"
